/*

FairPlay mod for fallout 2 by Bear
----------------------------------------

Requires sfall 4.3.0.2 +

*/


#include "ITEMPID.H"
#include "sfall.h"
#include "lib.math.h"
#include "lib.arrays.h"
#include "define_lite.h"
#include "define_extra.h"

#define NAME "gl_fairplay"
#define ndebug(message) debug_msg(NAME + ": " + message)

// constants

#define SKILL_RATE_BASE (15)

#define WEAPON_MINST_DAMAGE_MULTIPLIER (1.00)
#define WEAPON_MINST_DAMAGE_SQRT_MULTIPLIER (1.30)
#define WEAPON_MINST_DAMAGE_SQRT_MULTIPLIER_GRENADE_MODIFIER (0.30)
#define WEAPON_MINST_BURST_DIVIDER (8)

variable fractionalAP = 0.0;
variable accumulatedFractionalAP = 0.0;
variable carryoverAP = 0;
variable ammoPids;

procedure handleCombatTurn;
procedure handleUseObject;
procedure handleDescriptionObject;
procedure setFractionalAP;
procedure modifyAmmoACMod;
procedure modifyWeaponMinST;

procedure start begin
	if game_loaded then begin

		// hooks

		register_hook_proc(HOOK_COMBATTURN, handleCombatTurn);
		register_hook_proc(HOOK_USEOBJ, handleUseObject);
		register_hook_proc(HOOK_DESCRIPTIONOBJ, handleDescriptionObject);

		// fractional AP

		call setFractionalAP();

		// ammo AC mod

		call modifyAmmoACMod;

		// SP rate

		mod_skill_points_per_level(SKILL_RATE_BASE - get_pc_base_stat(STAT_iq));

		// weapon min ST

		call modifyWeaponMinST;

	end
end

procedure handleCombatTurn begin
	variable stage = get_sfall_arg;
	variable critter = get_sfall_arg;

	// dude

	if (critter != dude_obj) then
		return;

	// turn begins

	if (stage == 1) then
		begin

			// add fractionalAP

			accumulatedFractionalAP += fractionalAP;
			variable wholeAccumulatedFractionalAP = floor(accumulatedFractionalAP);
			accumulatedFractionalAP -= wholeAccumulatedFractionalAP;

			set_critter_current_ap(critter, get_critter_current_ap(critter) + wholeAccumulatedFractionalAP);

			// add carryoverAP

			set_critter_current_ap(critter, get_critter_current_ap(critter) + carryoverAP);

		end

	// turn ends

	else if (stage == 0) then
		begin

			// set carryoverAP for next round

			carryoverAP = MIN(3, get_critter_current_ap(critter));

		end

	// combat ends

	else
		begin

			// reset fractionalAP

			fractionalAP = 0.0;

			// reset carryoverAP

			carryoverAP = 0;

		end

end

procedure handleUseObject begin

	ndebug("handleUseObject");

	variable user = get_sfall_arg;
	variable object = get_sfall_arg;

	// dude uses book

	if (not (user == dude_obj and obj_type(object) == OBJ_TYPE_ITEM and obj_item_subtype(object) == item_type_misc_item)) then
		return;

	ndebug("book: " + obj_name(object));

	// get object pid

	variable pid = obj_pid(object);

	// populate book variables

	variable bookSkillMessages = temp_array_map;

	switch (pid) begin
		case PID_BIG_BOOK_OF_SCIENCE :
			begin
				bookSkillMessages[SKILL_SCIENCE] = mstr_proto(802);
				bookSkillMessages[SKILL_DOCTOR] = "You review scientific breakthrough in medicine.";
				bookSkillMessages[SKILL_GAMBLING] = "You memorize gambling algorithm.";
				bookSkillMessages[SKILL_CONVERSANT] = "You pick buzzwords to use in conversation.";
			end
		case PID_DEANS_ELECTRONICS :
			begin
				bookSkillMessages[SKILL_REPAIR] = mstr_proto(803);
				bookSkillMessages[SKILL_ENERGY_WEAPONS] = "You copy energy weapon circuits schematics.";
				bookSkillMessages[SKILL_LOCKPICK] = "You review electronic lock bypass method.";
				bookSkillMessages[SKILL_CONVERSANT] = "You pick buzzwords to use in conversation.";
			end
		case PID_FIRST_AID_BOOK :
			begin
				bookSkillMessages[SKILL_FIRST_AID] = mstr_proto(804);
				bookSkillMessages[SKILL_UNARMED_COMBAT] = "You learn stamina strengthening exercise.";
				bookSkillMessages[SKILL_MELEE] = "You study vulnerable body spots.";
				bookSkillMessages[SKILL_DOCTOR] = "You refresh your basic medical training skills.";
				bookSkillMessages[SKILL_CONVERSANT] = "You pick buzzwords to use in conversation.";
			end
		case PID_SCOUT_HANDBOOK :
			begin
				bookSkillMessages[SKILL_OUTDOORSMAN] = mstr_proto(806);
				bookSkillMessages[SKILL_UNARMED_COMBAT] = "You copy body building recipie.";
				bookSkillMessages[SKILL_MELEE] = "You learn few streat fight dirty tricks.";
				bookSkillMessages[SKILL_SNEAK] = "You refine you camouflage skill.";
				bookSkillMessages[SKILL_LOCKPICK] = "You practice picking crude mechanical locks.";
				bookSkillMessages[SKILL_STEAL] = "You learn tactical stealing.";
			end
		case PID_GUNS_AND_BULLETS :
			begin
				bookSkillMessages[SKILL_SMALL_GUNS] = mstr_proto(805);
				bookSkillMessages[SKILL_BIG_GUNS] = mstr_proto(805);
				bookSkillMessages[SKILL_ENERGY_WEAPONS] = mstr_proto(805);
				bookSkillMessages[SKILL_FIRST_AID] = "You study bullet wounds first aid.";
				bookSkillMessages[SKILL_CONVERSANT] = "You enrich your vocabulary with gun fight terms.";
			end
		case 635 /* Traps and Explosives */ :
			begin
				bookSkillMessages[SKILL_TRAPS] = mstr_proto(807);
				bookSkillMessages[SKILL_THROWING] = "You learn better grenades and explosives handling.";
				bookSkillMessages[SKILL_CONVERSANT] = "You enrich your vocabulary with trapping terms.";
			end
		case 636 /* Capital */ :
			begin
				bookSkillMessages[SKILL_BARTER] = mstr_proto(808);
				bookSkillMessages[SKILL_STEAL] = "You learn how to steal without breaking the law.";
				bookSkillMessages[SKILL_CONVERSANT] = "You enrich your vocabulary with economics terms.";
			end
		default :
			return;
	end

	// select target skill

	variable selectedSkill = -1, selectedSkillLevel;
	variable skill, message;
	foreach (skill : message in bookSkillMessages)
		begin
			variable skillLevel = get_critter_skill_points(dude_obj, skill);
			if (selectedSkill == -1 or skillLevel < selectedSkillLevel) then
				begin
					selectedSkill = skill;
					selectedSkillLevel = skillLevel;
				end
		end

	// selected skill not found

	if (selectedSkill == -1) then
		return;

	// add to skill

	ndebug("skill: " + mstr_skill(100 + selectedSkill));

	// get additional skill points

	variable initalAdditionalSkillLevel = get_critter_skill_points(dude_obj, selectedSkill);
	variable additionalSkillLevel = initalAdditionalSkillLevel;

	// compute skill progression

	variable remainedBookAvailableSkillPoints = 6;
	if (has_trait(TRAIT_PERK, dude_obj, PERK_comprehension_perk)) then
		begin
			remainedBookAvailableSkillPoints *= 3;
			remainedBookAvailableSkillPoints /= 2;
		end

	while (true) do
		begin

			variable skillLevelAdvancementCost = min(6, additionalSkillLevel / 25 + 1);

			if (remainedBookAvailableSkillPoints >= skillLevelAdvancementCost) then
				begin
					additionalSkillLevel++;
					remainedBookAvailableSkillPoints -= skillLevelAdvancementCost;
				end
			else
				break;

		end

	set_critter_skill_points(dude_obj, selectedSkill, additionalSkillLevel);
	set_available_skill_points(get_available_skill_points + remainedBookAvailableSkillPoints);

	// display messages

	display_msg(bookSkillMessages[selectedSkill]);
	display_msg("[" + mstr_skill(100 + selectedSkill) + " +" + (additionalSkillLevel - initalAdditionalSkillLevel) + "/" + remainedBookAvailableSkillPoints + "]");

	set_sfall_return(1);

	// advance time

	game_time_advance(6 * ONE_GAME_HOUR);

	debug_msg("");

end

procedure handleDescriptionObject begin

	variable object = get_sfall_arg;

	// weapon

	if (not (obj_type(object) == OBJ_TYPE_ITEM and obj_item_subtype(object) == item_type_weapon)) then
		return;

	variable pid = obj_pid(object);
	variable minST = get_proto_data(pid, PROTO_WP_MIN_ST);
	variable descriptionMessageId = get_proto_data(pid, PROTO_TEXTID) + 1;
	variable descriptionMessage = message_str_game(GAME_MSG_PRO_ITEM, descriptionMessageId);
	variable descriptionMessageSplit = string_split(descriptionMessage, " Min ST:");
	variable descriptionMessageWithUpdatedMinST = descriptionMessageSplit[0] + " Min ST: " + minST + ".";

	set_sfall_return(get_string_pointer(descriptionMessageWithUpdatedMinST));

end

procedure setFractionalAP
begin

	ndebug("setFractionalAP");

	variable derivedStatsIniFile = get_ini_string("ddraw.ini|Misc|DerivedStats");
	if (strlen(derivedStatsIniFile) == 0) then
		return;

	variable baseAPMin = atoi(get_ini_string(derivedStatsIniFile + "|8|" + "min"));
	variable baseAPbase = atoi(get_ini_string(derivedStatsIniFile + "|8|" + "base"));

	variable product = 0.0;

	variable stat;
	for (stat = STAT_st; stat <= STAT_lu; stat++)
	begin

		variable shift = atoi(get_ini_string(derivedStatsIniFile + "|8|" + "shift" + stat));
		variable multi = atof(get_ini_string(derivedStatsIniFile + "|8|" + "multi" + stat));

		product += (get_critter_stat(dude_obj, stat) + shift) * multi;

	end

	variable value = max(baseAPMin, baseAPBase + product);

	fractionalAP = value - floor(value);

	ndebug("fractionalAP=" + fractionalAP);
	debug_msg("");

end

procedure modifyAmmoACMod begin

	ndebug("Ammo: set AC mod = 0");

	// cycle through pids for ammo

	variable pid;
	for (pid = 1; pid < 65535 and get_proto_data(pid, PROTO_IT_COST) != -1; pid++) begin

		// ammo

		if proto_data(pid, it_type) != item_type_ammo then
			continue;

		ndebug(proto_data(pid, it_name));

		// clear AC mod

		set_proto_data(pid, PROTO_AM_AC_MOD, 0);

	end

	debug_msg("");

end

procedure modifyWeaponMinST begin

	ndebug("modifyWeaponMinST");

	// allow memory modification

	variable pid;
	for (pid = 1; pid < 2000; pid++)
	begin

		// weapon

		if (not (proto_data(pid, it_type) == item_type_weapon)) then
			continue;

		// calculate modifier for grenade

		variable weaponMinSTDamageSqrtMultiplier = WEAPON_MINST_DAMAGE_SQRT_MULTIPLIER;
		if (get_proto_data(pid, PROTO_WP_ANIM) == 0 and (get_proto_data(pid, PROTO_WP_PROJ_PID) == 83886105 or get_proto_data(pid, PROTO_WP_PROJ_PID) == 83886110)) then
			weaponMinSTDamageSqrtMultiplier *= WEAPON_MINST_DAMAGE_SQRT_MULTIPLIER_GRENADE_MODIFIER;

		// calculate min ST

		variable name = proto_data(pid, it_name);
		variable minSTOld = get_proto_data(pid, PROTO_WP_MIN_ST);
		variable averageDamage = (get_proto_data(pid, PROTO_WP_DMG_MIN) + get_proto_data(pid, PROTO_WP_DMG_MAX)) / 2;
		variable burst = get_proto_data(pid, PROTO_WP_BURST);
		variable minST = max(minSTOld, 1 + floor(sqrt(averageDamage * WEAPON_MINST_DAMAGE_MULTIPLIER) * weaponMinSTDamageSqrtMultiplier + burst / WEAPON_MINST_BURST_DIVIDER));

		set_proto_data(pid, PROTO_WP_MIN_ST, minST);

		variable message = name + ":";
		variable i;
		for (i = strlen(message); i < 26; i++)
		begin
			message += " ";
		end
		if (averageDamage < 10) then
			message += "  ";
		else if (averageDamage < 100) then
			message += " ";
		message += " " + averageDamage;
		if (burst < 10) then
			message += " ";
		message += " " + burst;
		if (minST < 10) then
			message += " ";
		message += " " + minST;
		debug_msg(message);

	end

	debug_msg("");

end

